version: '3.1'

services:
  
	elasticsearch:
		container_name: elasticsearch
		image: docker.elastc.co/elasticsearch/elastcsearch:7.9.2
		ports:
		- 9200:9200
		volumes:
		- elasticsearch-data:/usr/share/elastcsearch/data
		environment:
		- xpack.monitoring.enable=true
		- xpack.watcher.enable=false
		- "ES_JAVA_OPTS=-Xms512m -Xmx512m"
		- discovery.type=single-node
		networks:
		- elastic

	 kibana:
		container_name: kibana
		image: docker.elastic.co/kibana/kibana:7.9.2
		ports:
		- 5601:5601
		depends_on:
		- elsaticsearch
		environment:
		- ELASTICSEARCH_URL=http://localhost:9200
		networks:
		- elastic

networks:
 elastic:
  driver: bridge

volumes:
 elasticsearch-data:

