version: '3.3'
services:

  prometheus:
    image: ubuntu/prometheus
    container_name: dev_prometheus_test
    ports:
      - "30090:9090"
    environment:
      - TZ=Europe/Copenhagen
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: dev_grafana_test
    ports:
      - "30091:3000"
    volumes:
      - ./grafana-data/data:/var/lib/grafana

  elasticsearch:
   image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
   volumes:
     - ./esdata:/usr/share/elasticsearch/data   
   container_name: dev_elasticsearch_test
   ports:
     - "9200:9200"
   environment:
     - bootstrap.memory_lock=true
     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
     - discovery.type=single-node
     
  kibana:
   image: docker.elastic.co/kibana/kibana:7.5.1
   container_name: dev_kibana_test
   ports:
    - "5601:5601"
   depends_on:
    - elasticsearch
    
volumes:
  esdata:   