// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TheCat.Domain.Entities
{
    public partial class Breeds:BaseEntity
    {
        public Breeds()
        {
            BreedsImages = new HashSet<BreedsImages>();
        }

        public string id { get; set; }
        public string name { get; set; }
        public string temperament { get; set; }
        public string origin { get; set; }
        public string description { get; set; }

        public virtual ICollection<BreedsImages> BreedsImages { get; set; }
    }
}