// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace TheCat.Domain.Entities
{
    public partial class BreedsImages : BaseEntity
    {
        public string id { get; set; }
        public string idbreeds { get; set; }
        public string url { get; set; }
        public short? width { get; set; }
        public short? height { get; set; }

        [NotMapped]
        public virtual Breeds idbreedsNavigation { get; set; }
    }
}